---
# tasks file for stirlingpdf
- name: Install packages
  ansible.builtin.package:
    name:
      - automake
      - autoconf
      - libtool
      - libleptonica-dev
      - pkg-config
      - zlib1g-dev
      - make
      - g++
      - git
      - python3
      - python3-pip
    state: present

- name: Ensure corretto key is on remote
  ansible.builtin.apt_key:
    url: "{{ stirlingpdf_java_deb_key }}"
    keyring: /usr/share/keyrings/corretto-keyring.gpg
    state: present

- name: Ensure corretto repo is on remote
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/java.list
    content: "{{ stirlingpdf_java_deb_repo }}"
    owner: root
    group: root
    mode: 0644

- name: Update cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install Java packages
  ansible.builtin.package:
    name:
      - "{{ stirlingpdf_java_package }}"
      - libxi6
      - libxtst6
      - libxrender1
    state: present

- name: Clone jbig2enc
  ansible.builtin.git:
    repo: https://github.com/agl/jbig2enc.git
    dest: "{{ stirlingpdf_jbig2enc_path }}"
    update: true
    clone: true

- name: Autogen and configure jbig2enc
  ansible.builtin.shell:
    cmd: |
      ./autogen.sh
      ./configure
  args:
    chdir: "{{ stirlingpdf_jbig2enc_path }}"
  changed_when: false

- name: Install jbig2enc
  community.general.make:
    chdir: "{{ stirlingpdf_jbig2enc_path }}"
    target: install
  changed_when: false

- name: Install additional packages
  ansible.builtin.package:
    name:
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-impress
      - tesseract-ocr

- name: Set pip configuration
  ansible.builtin.command: pip3 config set global.break-system-packages True
  changed_when: false

- name: Install additional pip packages
  ansible.builtin.pip:
    name:   
      - uno
      - opencv-python-headless
      - unoconv
      - pngquant
      - WeasyPrint

- name: Clone Stirling PDF
  ansible.builtin.git:
    repo: https://github.com/Stirling-Tools/Stirling-PDF.git
    dest: "{{ stirlingpdf_build_path }}"
    update: true
    clone: true
    force: true

- name: Set chmod gradlew
  ansible.builtin.file:
    path: "{{ stirlingpdf_build_path }}/gradlew"
    mode: "0755"
    owner: root
    group: root

- name: Build Stirling PDF
  ansible.builtin.shell:
    cmd: ./gradlew build
  args:
    chdir: "{{ stirlingpdf_build_path }}"
  changed_when: false

- name: Stirling PDF jar name
  ansible.builtin.shell: ls {{ stirlingpdf_build_path }}/build/libs/Stirling-PDF-*.jar
  register: stirling_pdf_jar

- name: Move Stirling PDF jar
  ansible.builtin.file:
    src: "{{ stirling_pdf_jar.stdout }}"
    dest: "{{ stirlingpdf_path }} /Stirling-PDF.jar"
    owner: root
    group: root
    mode: "0755"

- name: Move Stirling PDF scripts
  ansible.builtin.copy:
    src: "{{ stirlingpdf_build_path }}/scripts"
    dest: "{{ stirlingpdf_path }}"
    owner: root
    group: root
    mode: "0755"

- name: Ensure Stirling PDF service file is on remote
  ansible.builtin.template:
    src: stirlingpdf.service.j2
    dest: /etc/systemd/system/stirlingpdf.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Wiki.js

- name: Ensure Stirling PDF service is started and enabled
  ansible.builtin.service:
    name: stirlingpdf
    state: started
    enabled: true
